# Manually Defined Role Mappings
/api/auth/token=API_AUTH_TOKEN_POST
/api/auth/introspect=API_AUTH_INTROSPECT_POST
/api/auth/logout=API_AUTH_LOGOUT_POST
/api/books=API_BOOKS_INDEX_POST
/api/books=API_BOOKS_INDEX_GET
/api/books/batch=API_BOOKS_BATCH_POST
/api/books/export=API_BOOKS_EXPORT_GET
/api/books/{title}=API_BOOKS_INDEX_GET
/api/books/{title}=API_BOOKS_INDEX_DELETE
/api/borrows=API_BORROWS_INDEX_POST
/api/borrows=API_BORROWS_INDEX_GET
/api/borrows/{borrowId}=API_BORROWS_INDEX_PUT
/api/borrows/{borrowId}=API_BORROWS_INDEX_DELETE
/api/borrows/{borrowId}=API_BORROWS_INDEX_GET
/api/borrows/{borrowId}/return=API_BORROWS_RETURN_POST
/api/borrows/user/{userId}=API_BORROWS_USER_GET
/api/categories=API_CATEGORIES_INDEX_POST
/api/categories=API_CATEGORIES_INDEX_GET
/api/categories/{id}=API_CATEGORIES_INDEX_PUT
/api/categories/{id}=API_CATEGORIES_INDEX_DELETE
/api/categories/{id}=API_CATEGORIES_INDEX_GET
/api/categories/batch=API_CATEGORIES_BATCH_POST
/api/categories/name/{name}=API_CATEGORIES_NAME_GET
/api/functions=API_FUNCTIONS_INDEX_POST
/api/functions=API_FUNCTIONS_INDEX_GET
/api/functions/{functionCode}=API_FUNCTIONS_INDEX_GET
/api/posts=API_POSTS_INDEX_POST
/api/posts/{postId}=API_POSTS_INDEX_PUT
/api/posts/{postId}=API_POSTS_INDEX_DELETE
/api/posts/search=API_POSTS_SEARCH_GET
/api/posts/like=API_POSTS_LIKE_POST
/api/posts/comment=API_POSTS_COMMENT_POST
/api/posts/{postId}/comments=API_POSTS_COMMENTS_GET
/api/roles=API_ROLES_INDEX_POST
/api/roles=API_ROLES_INDEX_GET
/api/roles/{id}=API_ROLES_INDEX_GET
/api/roles/{id}=API_ROLES_INDEX_DELETE
/api/role-functions=API_ROLE_FUNCTIONS_INDEX_POST
/api/role-functions/{roleId}=API_ROLE_FUNCTIONS_INDEX_GET
/api/role-functions/{roleGroupId}/functions=API_ROLE_FUNCTIONS_FUNCTIONS_GET
/api/users=API_USERS_INDEX_POST
/api/users=API_USERS_INDEX_GET
/api/users/{id}=API_USERS_INDEX_PUT
/api/users/{id}=API_USERS_INDEX_DELETE
/api/users/{id}=API_USERS_INDEX_GET
/api/users/{id}/status=API_USERS_STATUS_PATCH
/api/users/current=API_USERS_CURRENT_GET
/api/users/search=API_USERS_SEARCH_POST
/api/users/search/advanced=API_USERS_SEARCH_ADVANCED_GET